### PR TITLE
feat(telus-standard): use telus/standard

### PR DESCRIPTION
**Pull request by billxinli**

### CODE REVIEW

**Comment by ruxandrafed** [comment]
@billxinli any chance you can pls update some of those deps to get the check green? :D

**Comment by billxinli** [comment]
Screen Shot 2019-06-26 at 6 14 48 PM

Is TravisCI an option now as well?

**Comment by ruxandrafed** [comment]
@billxinli no, it shouldn't be .. eventually we will get rid of that too. Thanks for fixing :)

**Pull request merged**
